package net.minecraftforge.client.gui.overlay;

public enum VanillaGuiOverlay {
    VIGNETTE, SPYGLASS, HELMET, FROSTBITE, PORTAL, HOTBAR, CROSSHAIR, BOSS_EVENT_PROGRESS, PLAYER_HEALTH, ARMOR_LEVEL, FOOD_LEVEL, AIR_LEVEL, MOUNT_HEALTH, JUMP_BAR, EXPERIENCE_BAR, ITEM_NAME, SLEEP_FADE, POTION_ICONS, DEBUG_TEXT, FPS_GRAPH, RECORD_OVERLAY, TITLE_TEXT, SUBTITLES, SCOREBOARD, CHAT_PANEL, PLAYER_LIST;

    public NamedGuiOverlay type() {return null;}
}
