modLoader="javafml"
loaderVersion="[0,)"
license="MIT"
[[mods]]
modId="${MOD_ID}"
version="${MOD_VERSION}"
displayName="${MOD_TITLE}"
authors="${MOD_AUTHOR}"
description='''
在推流软件中捕获 “【直播模式】Minecraft” 窗口即可。
'''